In [4]:
import numpy as np
from numpy import linalg

1. Создайте numpy array с элементами от числа N до 0. Например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
def my_array(N):
    return np.arange(0, N)[::-1]
 
print(my_array(10))
print(my_array(15))
print(my_array(20))

[9 8 7 6 5 4 3 2 1 0]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
def sum_matrix(N):
    my_matrix = sum(sum(np.diag(np.arange(N, 0, -1))))
    return my_matrix
 
print(sum_matrix(5))
print(sum_matrix(10))
print(sum_matrix(15))

15
55
120


3. 
Решите систему уравнений:
```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [5]:
def solve_system_equations():
    a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
    b = np.array([4, 12, -3])
    return linalg.solve(a, b)

print(solve_system_equations())

[ 0.46666667  3.84444444 -5.55555556]


4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем.

Матрица в виде numpy array
```
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
```
На сайт заходит очередной посетитель, о покупках которого известно следующее:

```next_user_stats = np.array([0, 1, 2, 0, 0, 0])```
Найдите индекс самого похожего пользователя max_index, т.е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.
Нумерацию индексов следует начинать с 0

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

i = 0

bLength = np.linalg.norm(next_user_stats)

dict_ = {}

for key, value in enumerate(users_stats):
    
    while i < len(users_stats):
        result = np.linalg.norm(users_stats[key])
        dict_[key] = np.dot(users_stats[key], next_user_stats) / (result * bLength)
        i = i + 1
        key = key + 1
        
print(max(dict_, key=dict_.get))

7
